version: '2'

networks: 
  blockchain-network:
    driver: bridge

services:
  core-api:
    container_name: ${PROJECTNAME}-node-server
    #image: TODO
    build: .
    environment:
      NODE_ENV: ${NODE_ENV_DEV}
    ports:
      - "${HTTPPORT}:3000"
    volumes: 
      - .:/usr/src/app
    networks: 
      - blockchain-network    
  mongo-db:
    container_name: ${PROJECTNAME}-mongodb
    image: mongo:latest
    ports:
      - "${MONGODBPORT}:27018"
    volumes:
      - ./data/db:/data/db
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles --logpath=/dev/null
